classDiagram
  class ChatSession {
  }
  class KnowledgeEmbedding {
  }
  class SavedJob {
  }
  class ScamPattern {
  }
  class UserProvider {
  }
  class ApplicationMessage {
  }
  class JobApplication {
  }
  class JobAssignment {
  }
  class JobSkill {
  }
  class Job {
  }
  class JobCategory {
  }
  class Notification {
  }
  class Dispute {
  }
  class PaymentConfirmation {
  }
  class EmployerProfile {
  }
  class WorkerProfile {
  }
  class WorkerSkill {
  }
  class Report {
  }
  class Review {
  }
  class Skill {
  }
  class PaymentOrder {
  }
  class SubscriptionPlan {
  }
  class UsageCounter {
  }
  class UserSubscription {
  }
  class User {
  }
  class EkycResult {
  }
  class VerificationRequest {
  }
  class WorkerServiceEntity {
  }


