export enum AssignmentStatus {
  ASSIGNED = 'ASSIGNED',
  IN_PROGRESS = 'IN_PROGRESS',
  HOURS_SUBMITTED = 'HOURS_SUBMITTED',
  PAYMENT_PENDING = 'PAYMENT_PENDING',
  PAYMENT_SENT = 'PAYMENT_SENT',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}
