/**
 * Notification Type
 * FE will use this enum to handle different types of notifications
 */
export enum NotificationType {
  // System
  SYSTEM = 'SYSTEM',

  // Order
  ORDER_CREATED = 'ORDER_CREATED',
  ORDER_CONFIRMED = 'ORDER_CONFIRMED',
  ORDER_SHIPPED = 'ORDER_SHIPPED',
  ORDER_DELIVERED = 'ORDER_DELIVERED',
  ORDER_CANCELLED = 'ORDER_CANCELLED',

  // Payment
  PAYMENT_SUCCESS = 'PAYMENT_SUCCESS',
  PAYMENT_FAILED = 'PAYMENT_FAILED',

  // Social
  USER_FOLLOWED = 'USER_FOLLOWED',
  POST_LIKED = 'POST_LIKED',
  POST_COMMENTED = 'POST_COMMENTED',
  COMMENT_REPLIED = 'COMMENT_REPLIED',

  // Promotion
  PROMOTION = 'PROMOTION',

  // Job platform
  JOB_APPLICATION_RECEIVED = 'JOB_APPLICATION_RECEIVED',
  JOB_APPLICATION_ACCEPTED = 'JOB_APPLICATION_ACCEPTED',
  JOB_APPLICATION_REJECTED = 'JOB_APPLICATION_REJECTED',
  JOB_COMPLETED = 'JOB_COMPLETED',
  JOB_CANCELLED = 'JOB_CANCELLED',
  JOB_CHECKED_IN = 'JOB_CHECKED_IN',
  APPLICATION_CANCELLED = 'APPLICATION_CANCELLED',
  REVIEW_RECEIVED = 'REVIEW_RECEIVED',

  // Payment
  PAYMENT_CONFIRMED = 'PAYMENT_CONFIRMED',
  PAYMENT_DISPUTED = 'PAYMENT_DISPUTED',
  DISPUTE_RESOLVED = 'DISPUTE_RESOLVED',
}

/**
 * Reference Type - Type of referenced entity
 */
export enum ReferenceType {
  ORDER = 'ORDER',
  USER = 'USER',
  POST = 'POST',
  COMMENT = 'COMMENT',
  PRODUCT = 'PRODUCT',
  PROMOTION = 'PROMOTION',
  JOB = 'JOB',
  JOB_APPLICATION = 'JOB_APPLICATION',
  REVIEW = 'REVIEW',
  PAYMENT = 'PAYMENT',
  DISPUTE = 'DISPUTE',
}
